-- notice_preprocessed 테이블 생성
-- 전처리된 공고 데이터 (수치형, 범주형, 텍스트 임베딩)

CREATE TABLE IF NOT EXISTS tmp.notice_preprocessed (
    -- Primary Key
    bidntceno TEXT NOT NULL,
    bidntceord TEXT NOT NULL,

-- 수치형 컬럼 (원본)
totprdprcnum DOUBLE PRECISION,
drwtprdprcnum DOUBLE PRECISION,
bdgtamt DOUBLE PRECISION,
presmptprce DOUBLE PRECISION,
govsplyamt DOUBLE PRECISION,
indstrytyevlrt DOUBLE PRECISION,
maincnsttycnstwkprearngamt DOUBLE PRECISION,
contrctrcnstrtngovsplymtrlamt DOUBLE PRECISION,
govcnstrtngovsplymtrlamt DOUBLE PRECISION,
sucsfbidlwltrate DOUBLE PRECISION,
bssamt DOUBLE PRECISION,
rsrvtnprcerngbgnrate DOUBLE PRECISION,
rsrvtnprcerngendrate DOUBLE PRECISION,
evlbssamt DOUBLE PRECISION,
dfcltydgrcfcnt DOUBLE PRECISION,
etcgnrlexpnsbssrate DOUBLE PRECISION,
gnrlmngcstbssrate DOUBLE PRECISION,
prftbssrate DOUBLE PRECISION,
lbrcstbssrate DOUBLE PRECISION,
sftymngcst DOUBLE PRECISION,
sftychckmngcst DOUBLE PRECISION,
rtrfundnon DOUBLE PRECISION,
envcnsrvcst DOUBLE PRECISION,
scontrctpayprcepaygrntyfee DOUBLE PRECISION,
mrfnhealthinsrprm DOUBLE PRECISION,
npninsrprm DOUBLE PRECISION,
odsnlngtrmrcprinsrprm DOUBLE PRECISION,
bssamtpurcnstcst DOUBLE PRECISION,
qltymngcst DOUBLE PRECISION,

-- 수치형 컬럼 (NULL 여부 플래그)
totprdprcnum_is_null DOUBLE PRECISION,
drwtprdprcnum_is_null DOUBLE PRECISION,
bdgtamt_is_null DOUBLE PRECISION,
presmptprce_is_null DOUBLE PRECISION,
govsplyamt_is_null DOUBLE PRECISION,
indstrytyevlrt_is_null DOUBLE PRECISION,
maincnsttycnstwkprearngamt_is_null DOUBLE PRECISION,
contrctrcnstrtngovsplymtrlamt_is_null DOUBLE PRECISION,
govcnstrtngovsplymtrlamt_is_null DOUBLE PRECISION,
sucsfbidlwltrate_is_null DOUBLE PRECISION,
bssamt_is_null DOUBLE PRECISION,
rsrvtnprcerngbgnrate_is_null DOUBLE PRECISION,
rsrvtnprcerngendrate_is_null DOUBLE PRECISION,
evlbssamt_is_null DOUBLE PRECISION,
dfcltydgrcfcnt_is_null DOUBLE PRECISION,
etcgnrlexpnsbssrate_is_null DOUBLE PRECISION,
gnrlmngcstbssrate_is_null DOUBLE PRECISION,
prftbssrate_is_null DOUBLE PRECISION,
lbrcstbssrate_is_null DOUBLE PRECISION,
sftymngcst_is_null DOUBLE PRECISION,
sftychckmngcst_is_null DOUBLE PRECISION,
rtrfundnon_is_null DOUBLE PRECISION,
envcnsrvcst_is_null DOUBLE PRECISION,
scontrctpayprcepaygrntyfee_is_null DOUBLE PRECISION,
mrfnhealthinsrprm_is_null DOUBLE PRECISION,
npninsrprm_is_null DOUBLE PRECISION,
odsnlngtrmrcprinsrprm_is_null DOUBLE PRECISION,
bssamtpurcnstcst_is_null DOUBLE PRECISION,
qltymngcst_is_null DOUBLE PRECISION,

-- 범주형 컬럼 (인코딩된 값)
rentceyn BIGINT,
intrbidyn BIGINT,
ntceinsttcd BIGINT,
dminsttcd BIGINT,
bidmethdnm BIGINT,
cntrctcnclsmthdnm BIGINT,
cmmnspldmdagrmntrcptdocmethd BIGINT,
rbidpermsnyn BIGINT,
arsltappldocrcptmthdnm BIGINT,
dtlsbidyn BIGINT,
bidprtcptlmtyn BIGINT,
prearngprcedcsnmthdnm BIGINT,
aplbsscntnts BIGINT,
maincnsttynm BIGINT,
cmmnspldmdcnum BIGINT,
cmmnspldmdmethdnm BIGINT,
brffcbidprcpermsnyn BIGINT,
dsgntcmptyn BIGINT,
arsltcmptyn BIGINT,
pqevalyn BIGINT,
rsrvtnprceremkngmthdnm BIGINT,
sucsfbidmthdcd BIGINT,
sucsfbidmthdnm BIGINT,
indstrytylmtyn BIGINT,
cnstrtsitergnnm BIGINT,
rgndutyjntcontrctyn BIGINT,
ciblaplyn BIGINT,
mtltyadvcpsblyn BIGINT,
bidprcecalclayn BIGINT,
qltymngcstaobjyn BIGINT,

-- 범주형 컬럼 (NULL 여부 플래그)
rentceyn_is_null DOUBLE PRECISION,
intrbidyn_is_null DOUBLE PRECISION,
ntceinsttcd_is_null DOUBLE PRECISION,
dminsttcd_is_null DOUBLE PRECISION,
bidmethdnm_is_null DOUBLE PRECISION,
cntrctcnclsmthdnm_is_null DOUBLE PRECISION,
cmmnspldmdagrmntrcptdocmethd_is_null DOUBLE PRECISION,
rbidpermsnyn_is_null DOUBLE PRECISION,
arsltappldocrcptmthdnm_is_null DOUBLE PRECISION,
dtlsbidyn_is_null DOUBLE PRECISION,
bidprtcptlmtyn_is_null DOUBLE PRECISION,
prearngprcedcsnmthdnm_is_null DOUBLE PRECISION,
aplbsscntnts_is_null DOUBLE PRECISION,
maincnsttynm_is_null DOUBLE PRECISION,
cmmnspldmdcnum_is_null DOUBLE PRECISION,
cmmnspldmdmethdnm_is_null DOUBLE PRECISION,
brffcbidprcpermsnyn_is_null DOUBLE PRECISION,
dsgntcmptyn_is_null DOUBLE PRECISION,
arsltcmptyn_is_null DOUBLE PRECISION,
pqevalyn_is_null DOUBLE PRECISION,
rsrvtnprceremkngmthdnm_is_null DOUBLE PRECISION,
sucsfbidmthdcd_is_null DOUBLE PRECISION,
sucsfbidmthdnm_is_null DOUBLE PRECISION,
indstrytylmtyn_is_null DOUBLE PRECISION,
cnstrtsitergnnm_is_null DOUBLE PRECISION,
rgndutyjntcontrctyn_is_null DOUBLE PRECISION,
ciblaplyn_is_null DOUBLE PRECISION,
mtltyadvcpsblyn_is_null DOUBLE PRECISION,
bidprcecalclayn_is_null DOUBLE PRECISION,
qltymngcstaobjyn_is_null DOUBLE PRECISION,

-- 텍스트 임베딩 (pgvector)
bidntcenm vector,

-- Primary Key 제약조건
PRIMARY KEY (bidntceno, bidntceord) );

-- 코멘트
COMMENT ON TABLE step1.notice_preprocessed IS '전처리된 공고 데이터 (수치형, 범주형, 텍스트 임베딩)';

COMMENT ON COLUMN step1.notice_preprocessed.bidntceno IS '공고번호 (Primary Key)';

COMMENT ON COLUMN step1.notice_preprocessed.bidntceord IS '공고차수 (Primary Key)';

COMMENT ON COLUMN step1.notice_preprocessed.bidntcenm IS '공고명 텍스트 임베딩 (pgvector)';